spring.application.name=source-base

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.org.hibernate.SQL=${HIBERNATE_SQL_LOG_LEVEL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=${HIBERNATE_BIND_LOG_LEVEL:TRACE}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_DATA_REDIS_SSL_ENABLED:false}
spring.data.redis.timeout=3s
spring.data.redis.repositories.enabled=false

spring.cache.type=redis
spring.cache.redis.time-to-live=10m

management.endpoints.web.exposure.include=health,info

source-base.security.permit-all=false
source-base.security.jwt.token-expiration-time=900
source-base.security.jwt.refresh-token-exp-time=604800
source-base.security.jwt.token-issuer=source-base
source-base.security.jwt.token-signing-key=${SOURCE_BASE_JWT_TOKEN_SIGNING_KEY}
source-base.queue.enabled=true
source-base.queue.default-topic=platform.events
